name: Build

on:
  workflow_dispatch:
  schedule:
    - cron: 0 19 * * 1

env:
  CLASH_ARCH: amd64
  TZ: Asia/Shanghai

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - name: Initialization Environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo timedatectl set-timezone "${TZ}"

    - name: Checkout
      uses: actions/checkout@mav4

    - name: Setup Go  
      uses: actions/setup-go@v5
      with:
        go-version: "1.22"
        check-latest: true

    - name: Setup UPX
      run: |
        cd ..
        wget https://github.com/upx/upx/releases/download/v4.2.4/upx-4.2.4-amd64_linux.tar.xz
        tar xf upx-4.2.4-amd64_linux.tar.xz
        echo "upx=../upx-4.2.4-amd64_linux/upx" >> $GITHUB_ENV

    - name: Download Files
      run: |
        curl -O ${{ secrets.PPGW }}
        curl -O https://raw.githubusercontent.com/alecthw/mmdb_china_ip_list/release/Country.mmdb

    - name: Build Mihomo
      env:
        GOBUILD: CGO_ENABLED=0 go build -tags with_gvisor -trimpath -ldflags '-w -s -buildid='
        BINDIR: bin
      run: |
        git clone -b Alpha https://github.com/MetaCubeX/mihomo
        cd mihomo
        mkdir ${BINDIR}
        GOARCH=${CLASH_ARCH} GOOS=linux ${GOBUILD} -o ${BINDIR}/clash
        cp ${BINDIR}/clash ../clash
      
    - name: Build PaoPaoGateWay
      run: |
        ls -la
        docker pull sliamb/ppgwiso:fullmod
        docker run --rm -e SNIFF=yes -v .:/data sliamb/ppgwiso:fullmod

    - name: Upload ISO To Artifact
      if: ${{  success() }}
      uses: actions/upload-artifact@main
      with:
        name: paopao-gateway
        path: |
          *.iso
      
