name: Build

on:
  workflow_dispatch:
  schedule:
    - cron: 0 19 * * 1

env:
  CLASH_KERNEL: amd64
  TZ: Asia/Shanghai

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - name: Initialization Environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo timedatectl set-timezone "${TZ}"

    - name: Checkout
      uses: actions/checkout@main

    - name: Download Files
      run: |
        curl -O ${{ secrets.PPGW }}
        curl -O https://raw.githubusercontent.com/alecthw/mmdb_china_ip_list/release/Country.mmdb
        wget -qO- https://raw.githubusercontent.com/vernesong/OpenClash/core/dev/meta/clash-linux-${CLASH_KERNEL}.tar.gz | tar xOvz > clash
        chmod +x clash

    - name: Build
      run: |
        docker pull sliamb/ppgwiso:fullmod
        docker run --rm -v .:/data sliamb/ppgwiso:fullmod

    - name: Upload ISO To Artifact
      if: ${{  success() }}
      uses: actions/upload-artifact@main
      with:
        name: paopao-gateway.iso
        path: |
          *.iso
      
